[package]
name = "evernote2turtl"
version = "0.1.0"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

[dependencies]
regex = "1"
lazy_static = "1"
html2md = "0.2"
json = "0.12"
zip = "0.6"
uuid = { version = "1", features = ["serde", "v4"] }
